### ISSUE TITLE
PDOException: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens

### ISSUE THREAD

**Issue by videni** [theofidry/AliceDataFixtures#109]
it seems there is bug in this bundle which costs me a whole day.   when  doctrine tries to insert `adAsset2`  into database , it gives the error
```
PDOException: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens
```
as you can see below, the AdAsset is the same Area entity, the later has no problem. why did this happen?  I found out that the original id generator can't alway be restored.  the exception will disappear if remove ` false === $generator->isPostInsertGenerator()` .

theofidry/alice-data-fixtures/src/Bridge/Doctrine/Persister/ObjectManagerPersister.php
```
    public function persist($object)
 {
            //....
            // this can't always restore the original generator.
            if (null !== $generator && false === $generator->isPostInsertGenerator()) {
                // Restore the generator if has been temporary unset
                $metadata->setIdGeneratorType($generatorType);
                $metadata->setIdGenerator($generator);
            }
 }
```

fixture.yml
```
App\Bundle\AdvertisementBundle\Entity\Advertisement:
    ad1:
        deviceType: 'pad'
        name: '欢度中秋节'
        status: 'published'
        channel: '上海闵行店'
        city: '上海'
        channelId: 10
        link: 'http://example.com'
        startsAt: "<date_create()>"
        endsAt: "<date_create('2 day')>"
        template: 'dark'
        bannerLink: '/test.png'
        assets: ['@adAsset1']
        organization: '<entityReference("App\Bundle\OrganizationBundle\Entity\Organization", "findOneByName", "Main")>'
    ad2:
        deviceType: 'pad'
        name: '欢度国庆'
        status: 'published'
        channel: '成都高新店'
        city: '成都'
        channelId: 11
        link: 'http://example.com'
        startsAt: "<date_create()>"
        endsAt: "<date_create('2 day')>"
        template: 'dark'
        bannerLink: '/test.png'
        assets: ['@adAsset2']
        organization: '<entityReference("App\Bundle\OrganizationBundle\Entity\Organization", "findOneByName", "Second")>'

App\Bundle\AdvertisementBundle\Entity\Area:
    area1:
        name: '生鲜区'
        areaId: 10
        advertisement: '@ad1'
    area2:
        name: '熟食区'
        areaId: 11
        advertisement: '@ad2'

App\Bundle\AdvertisementBundle\Entity\AdAsset:
    adAsset1:
        advertisement: '@ad1'
        originalName: 'none'
        mineType: 'image/png'
        path: '/test.png'
    adAsset2:
        advertisement: '@ad2'
        originalName: 'none2'
        mineType: 'image/png'
        path: '/test2.png'

```

call stack
```
tring(104) "/Users/acme/www/demo_app/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php278"
array(1) {
  ["app_advertisement_asset"]=>
  array(4) {
    ["path"]=>
    string(9) "/test.png"
    ["mine_type"]=>
    string(9) "image/png"
    ["original_name"]=>
    string(4) "none"
    ["advertisement_id"]=>
    int(159)
  }
}
string(115) "/Users/acme/www/demo_app/vendor/theofidry/alice-data-fixtures/src/Bridge/Doctrine/Persister/ObjectManagerPersister.php"
array(1) {
  ["id"]=>
  int(98)
}
string(115) "/Users/acme/www/demo_app/vendor/theofidry/alice-data-fixtures/src/Bridge/Doctrine/Persister/ObjectManagerPersister.php"
array(0) {
}
string(104) "/Users/acme/www/demo_app/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php278"
array(1) {
  ["app_advertisement_asset"]=>
  array(5) {
    ["path"]=>
    string(10) "/test2.png"
    ["mine_type"]=>
    string(9) "image/png"
    ["original_name"]=>
    string(5) "none2"
    ["id"]=>
    NULL
    ["advertisement_id"]=>
    int(160)
  }
}


Time: 19.74 seconds, Memory: 156.26MB

There was 1 error:

1) App\Tests\Controller\AddvertisementApiTest::it_allows_to_get_paginated_advertisement
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO app_advertisement_asset (path, mine_type, original_name, advertisement_id) VALUES (?, ?, ?, ?)' with params ["\/test2.png", "image\/png", "none2", null, 160]:

SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens

/Users/acme/www/demo_app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:126
/Users/acme/www/demo_app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:184
/Users/acme/www/demo_app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:158
/Users/acme/www/demo_app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php:178
/Users/acme/www/demo_app/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php:288
/Users/acme/www/demo_app/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:1100
/Users/acme/www/demo_app/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:386
/Users/acme/www/demo_app/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:362
/Users/acme/www/demo_app/vendor/theofidry/alice-data-fixtures/src/Bridge/Doctrine/Persister/ObjectManagerPersister.php:110
/Users/acme/www/demo_app/vendor/theofidry/alice-data-fixtures/src/Loader/PersisterLoader.php:91
/Users/acme/www/demo_app/vendor/theofidry/alice-data-fixtures/src/Loader/PurgerLoader.php:119
/Users/acme/www/demo_app/vendor/lakion/api-test-case/src/ApiTestCase.php:305
/Users/acme/www/demo_app/tests/Controller/AdvertisementApiTest.php:22
```
