### ISSUE TITLE
Use with Gedmo\TreeClosure - Cannot persist entities

### ISSUE THREAD

**Issue by petegore** [theofidry/AliceDataFixtures#118]
Hello,

I use the Gedmo @Tree and @TreeClosure for many of my entities.
For example : 

```
AppBundle\Entity\Node\ActivityType:
    activity_type_1:
        description: ""
        level: 1

    activity_type_2n:
        parent: '@activity_type_1'
            description: ""
            level: 1
```

When I run the fixtures I got the following error : 

```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'ancestor' cannot be null
```

When checking a valid DB, I can see that Gedmo create a closure entry even for an entity that don't have any parent, by setting itself as the parent and the child. So I tried to self-reference the first entity : 

```
AppBundle\Entity\Node\ActivityType:
    activity_type_1:
        parent: '@activity_type_1'
        description: ""
        level: 1

    activity_type_2n:
        parent: '@activity_type_1'
            description: ""
            level: 1
```

Then I got this message : 

```
[Doctrine\ORM\ORMInvalidArgumentException]
Binding entities to query parameters only allowed for entities that have an identifier.
```

I got desperate. I cannot find any example of fixtures with Gedmo\Tree on the web.
Is this a bug of Alice ?
