### ISSUE TITLE
Installation problem with PHPCR

### ISSUE THREAD

**Issue by benr77** [theofidry/AliceDataFixtures#124]
Trying to install this package in Symfony 4.3.15 after installing PHPCR dependencies:

`composer require doctrine/phpcr-bundle jackalope/jackalope-doctrine-dbal doctrine/phpcr-odm`

Have configuration as follows:
```
fidry_alice_data_fixtures:
    db_drivers:
        doctrine_orm: ~
        doctrine_phpcr_odm: ~
```

Get the following error message:

`The service "fidry_alice_data_fixtures.persistence.purger_factory.doctrine_phpcr" has a dependency on a non-existent service "doctrine_phpcr.odm.document_manager".`

Any ideas what is going wrong? Thanks
