### ISSUE TITLE
Bug or my mistake?

### ISSUE THREAD

**Issue by vittore** [theofidry/AliceDataFixtures#149]
Using this setup (I reports only relevant sections):

```
File: composer.json
        "theofidry/alice-data-fixtures": "^1.2",
        "doctrine/data-fixtures": "^1.4",
        "doctrine/doctrine-bundle": "^2.1",
        "doctrine/orm": "^2.7",
```

```
# behat.yml
default:
  autoload:
    '': '%paths.base%/behavior_test/bootstrap'
  suites:
    default:
      paths: [ '%paths.base%/behavior_test/features/' ]
      contexts:
        - FeatureContext:
            kernel: '@kernel'
        - SystemContext:
            kernel: '@kernel'
        - FixtureContext:
            doctrine: '@doctrine'
            loader: '@fidry_alice_data_fixtures.doctrine.persister_loader'
            fixturesBasePath: '%paths.base%/behavior_test/fixtures/'
```

When I run behat I get this error:
```

In ObjectManagerPersister.php line 42:

  Argument 1 passed to Fidry\AliceDataFixtures\Bridge\Doctrine\Persister\ObjectManagerPersister::__construct() must be an instance of Fidry\AliceDataFixtures\Bridge\Doctrine\Persister\Doctrine\ORM\EntityManager, instance of Doctrine\ORM\EntityManager given, called in var/cache/test/ContainerSyxKgsK/srcApp_KernelTestDebugContainer.php on line 1168

```

But if I change the _constructor of class/file vendor/theofidry/alice-data-fixtures/src/Bridge/Doctrine/Persister/ObjectManagerPersister.php
From:
```
public function __construct(ObjectManager $manager)
```
To:
```
public function __construct(\Doctrine\ORM\EntityManager $manager)
```

Then all works fine.
Is it a bug or a my mistake?

Thanks in advance.
Vittore
