### ISSUE TITLE
Since 1.3.1, fixture doesn't respect the provided ID.

### ISSUE THREAD

**Issue by VincentLanglet** [theofidry/AliceDataFixtures#153]
Before 1.3.1 version, the following fixtures
```
App\Entity\Bar
    bar1:
        id: 1
        foo: @foo1
    bar2:
        id: 2
        foo: @foo3
App\Entity\Foo
    foo1:
        id: 1
        name: foo1
    foo2:
        id: 2
        name: foo2
    foo3:
        id: 3
        name: foo3
```
Were correctly imported, with the provided ID

Since https://github.com/theofidry/AliceDataFixtures/pull/152, the ID provided are not respected anymore
- foo3 has the ID 2 since it's persisted by bar2
- foo2 has the ID 3 then

Firstly, this make failing a lot of my tests so this shouldn't be considered as a bugFix, more like a bug or a BC-break.
Secondly, I think the ID provided should always have the priority ; so I think that #152 is not the right fix of the #151 issue.
