### ISSUE TITLE
Doctrine decimal problem

### ISSUE THREAD

**Issue by studiomado** [theofidry/AliceDataFixtures#17]
I have this fixture:

```yaml
GammaBundle\Entity\Agent:
    agent1:
        codiceDitta: 100
        codiceAgent: 'A1'
        descrizione: <text(30)>
```

and this Doctrine entity property:

```php
   /**
     * @var decimal
     *
     * @ORM\Column(name="gam20_mg17_ditta_cg18", type="decimal", precision=5, scale=0)
     * @JMS\Expose
     */
    private $codiceDitta;
```

when I run `php bin/console hautelook:fixtures:load`, I got this error:

```
[Nelmio\Alice\Exception\Generator\Hydrator\InvalidArgumentException]                                          
  Invalid value given for the property "codiceDitta" of the object "agent1" (class: GammaBundle\Entity\Agent).  
                                                                                                                                                                                          
  [Symfony\Component\PropertyAccess\Exception\InvalidArgumentException]   
  Expected argument of type "GammaBundle\Entity\decimal", "double" given  
```

Any suggestion?
