### ISSUE TITLE
Persister decoration doesn't work

### ISSUE THREAD

**Issue by bravik** [theofidry/AliceDataFixtures#170]
Hi,

I'm trying to decorate the `Fidry\AliceDataFixtures\Bridge\Doctrine\Persister\ObjectManagerPersister`:
```yaml
services:
    Macroactive\App\Fixtures\CustomPersister:
        arguments:
            $defaultPersister: '@.inner'
        decorates: 'fidry_alice_data_fixtures.persistence.persister.doctrine.object_manager_persister'
```

However it doesn't work.

When I debug container, it seems that services are linked correctly:
![image](https://user-images.githubusercontent.com/1075618/109089215-9a0a6080-775c-11eb-987c-cb1574fee0bd.png)

However when I dump `$this->persister` in `PersisterLoader` it still gets default ObjectManagerPersister:
![image](https://user-images.githubusercontent.com/1075618/109089310-c1f9c400-775c-11eb-8600-e2a0741ee763.png)

I've also tried to override the persister, but it doesn't work either.
Is there anything missing?
