### ISSUE TITLE
Issue with fixtures persistence order due to doctrine/orm change

### ISSUE THREAD

**Issue by adrienfr** [theofidry/AliceDataFixtures#224]
Hi,

Since [doctrine/orm 2.16](https://github.com/doctrine/orm/blob/2.16.x/UPGRADE.md#potential-changes-to-the-order-in-which-inserts-are-executed), entities are not anymore processed in the same order than it was before :

> Do not make any assumptions in your code about the number of queries
>      it takes to flush changes, about the ordering of ``INSERT``, ``UPDATE``
>      and ``DELETE`` queries or the order in which entities will be processed.

So if I have a fixture file like below:
```
App\Entity\Currency:
    currency1:
        from_currency: EUR
        to_currency: USD
        rate: 1.1320
    currency2:
        from_currency: EUR
        to_currency: GBP
        rate: 0.8855
    currency3:
        from_currency: USD
        to_currency: EUR
        rate: 0.8832
```
I can't anymore rely on the fact that `$this->em->getRepository(Currency::class)->findAll()[0]`will be `currency1`.

Would it be possible to ensure that our entity fixtures are inserted in the exact same order that they are sorted in our fixture files? Sometimes entities don't have any timestamp to rely on and the incremental ID is the only way to order them properly.

I'm not sure how this could be done, as with entities with relations (OneToMany, ManyToOne, ...) it could be an issue to flush earlier?

Thanks
