### ISSUE TITLE
Flush between files

### ISSUE THREAD

**Issue by nicolassing** [theofidry/AliceDataFixtures#64]
Hello,

In beta5, objects were flushed between each file.
In the recent RC, they're not. I have many bugs because manyToOne relationships are not persisted to database :( 
It's a bug or a new features ? 

Thx !

**Comment by theofidry** [comment]
Hi,

Indeed there is a big change at this level: now the number of files doesn't matter, the data parsed by the files is merged into one to load the objects and then those objects are all persisted in one go. This is an intended behaviour for the new version to be able to deal with circular references.

What kind of issue do you encounter with your many to one relationships?

**Comment by nicolassing** [comment]
In some entities I don't configure cascade operations because the object have to exist in my business logic

**Comment by theofidry** [comment]
I'm not sure on how you are using the fixtures, but an easy solution would be to customize how your objects are persisted, I think this doc entry covers that: https://github.com/hautelook/AliceBundle/blob/master/doc/advanced-usage.md#persisting-the-classes-in-a-specific-order

**Comment by nicolassing** [comment]
I will try your solution !

BTW an example of my setup : 
```yaml
#1_company.yml
AppBundle\Entity\Company:
    company_acme:
        name: Acme

#2_mission.yml
AppBundle\Entity\Mission:
    mission_1:
        postalCode: '75002'
        city: 'Paris'
        company: '@company_acme'
```

when I look at my sql log. There is no INSERT.
