### ISSUE TITLE
Other database relation with null id since alice v3

### ISSUE THREAD

**Issue by Soullivaneuh** [theofidry/AliceDataFixtures#94]
I'm not sure if it's a bug or an old exploit of the v2 that was fixed with v3 and your package. I have two different MySQL databases with a "relation" between them:

```php
/**
 * Note: Most of the fields are null by default on the structure, but they are never like that.
 * This is why we don't set |null on properties here. This may be updated on the database side later.
 *
 * @ORM\Table(name="domains", indexes={
 *     @ORM\Index(name="name_index", columns={"name"})
 * })
 * @ORM\Entity(repositoryClass="PowerDNSBundle\Repository\PowerDNSDomainRepository")
 * @ORM\EntityListeners({"PowerDNSBundle\Listener\Entity\PowerDNSDomainEntityListener"})
 * @ORM\HasLifecycleCallbacks
 * @DoctrineAssert\UniqueEntity({"name"})
 */
class PowerDNSDomain
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255, nullable=false)
     * @Assert\NotBlank
     * @Assert\Regex("/^[[:alnum:]-\.]+$/u")
     */
    private $name;

    // Other properties...

    /**
     * @var int|null
     *
     * @ORM\Column(name="owner_id", type="integer", nullable=true)
     */
    private $ownerId;

    /**
     * @var User|null
     */
    private $owner;

    public function setOwnerId(?int $ownerId): self
    {
        $this->ownerId = $ownerId;

        return $this;
    }

    public function getOwnerId(): ?int
    {
        return $this->ownerId;
    }

    public function setOwner(User $owner): self
    {
        $this->owner = $owner;
        $this->setOwnerId($this->owner->getId());

        return $this;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }
}
```

This entity come from the other database. As you can see, I set the owner id while calling `setOwner`.

Not sure if it's the best solution at all, but it was working well with alive v2 and this fixture file:

```yaml
PowerDNSBundle\Entity\PowerDNSDomain:
    power_dns_domain_user_default:
        name: user-default.com
        owner: '@user_default'
    power_dns_domain_user_super_admin:
        name: super-admin.com
        owner: '@user_super_admin'
```

Since v3, the user object seems to not be persisted before the powerdns domain, and the id is `null`.

Is that normal? Which difference can make this issue?

Thanks.

**Comment by Soullivaneuh** [comment]
I did fix my issue with this listener method:

```php
final class PowerDNSDomainEntityListener
{
    /**
     * @var EntityManagerInterface
     */
    private $defaultEntityManager;

    /**
     * @required
     */
    public function setDefaultEntityManager(EntityManagerInterface $defaultEntityManager): void
    {
        $this->defaultEntityManager = $defaultEntityManager;
    }

    public function prePersist(PowerDNSDomain $dnsDomain): void
    {
        if (null !== $dnsDomain->getOwner() && null === $dnsDomain->getOwnerId()) {
            $dnsDomain->setOwnerId(
                $dnsDomain->getOwner()->getId()
            );
        }
    }
}
```

But I'm still curious to know the difference. Also, maybe there is a way to define a persistence priority (persist fixtures for one database, then the other?)?

**Comment by Soullivaneuh** [comment]
Well, the issue is we can not set a property without a setter anymore:

```
1) Tests\AppBundle\Controller\Billing\InvoiceControllerTest::testShow
Nelmio\Alice\Throwable\Exception\Generator\Hydrator\NoSuchPropertyException: Could not hydrate the property "id" of the object "accounting_fr" (class: AppBundle\Entity\Accounting).

/code/vendor/nelmio/alice/src/Throwable/Exception/Generator/Hydrator/HydrationExceptionFactory.php:85
/code/vendor/nelmio/alice/src/Generator/Hydrator/Property/SymfonyPropertyAccessorHydrator.php:62
/code/vendor/nelmio/alice/src/Generator/Hydrator/SimpleHydrator.php:91
/code/vendor/nelmio/alice/src/Generator/ObjectGenerator/SimpleObjectGenerator.php:106
/code/vendor/nelmio/alice/src/Generator/ObjectGenerator/SimpleObjectGenerator.php:94
/code/vendor/nelmio/alice/src/Generator/ObjectGenerator/CompleteObjectGenerator.php:53
/code/vendor/nelmio/alice/src/Generator/DoublePassGenerator.php:61
/code/vendor/nelmio/alice/src/Generator/DoublePassGenerator.php:51
/code/vendor/nelmio/alice/src/Loader/SimpleDataLoader.php:49
/code/vendor/nelmio/alice/src/Loader/SimpleFilesLoader.php:65
/code/vendor/theofidry/alice-data-fixtures/src/Loader/SimpleLoader.php:53
/code/var/cache/test/ContainerVzixhjb/SimpleLoader_4473cb1.php:27
/code/vendor/theofidry/alice-data-fixtures/src/Loader/PersisterLoader.php:77
/code/var/cache/test/ContainerVzixhjb/PersisterLoader_c8a8e24.php:34
/code/vendor/theofidry/alice-data-fixtures/src/Loader/PurgerLoader.php:119
/code/var/cache/test/ContainerVzixhjb/PurgerLoader_cb68499.php:34
/code/vendor/liip/functional-test-bundle/src/Test/WebTestCase.php:530
/code/tests/AppBundle/Controller/WebTestCase.php:35

Caused by
Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: Could not determine access type for property "id" in class "AppBundle\Entity\Accounting".
```

And I would like to not setup a `setId` method just for the fixture loading.

**Comment by theofidry** [comment]
You can use a custom [property accessor](https://github.com/nelmio/alice/blob/master/doc/advanced-guide.md#custom-accessor) for that case

**Comment by Soullivaneuh** [comment]
Oh right thanks, I'll take a look.

But still, why not using reflection in case of id properties?

**Comment by Soullivaneuh** [comment]
> Not all IDs are called "id" so it wouldn't only half work.

I assume it can be found with Doctrine metadata. I don't know for the other layers.

But not a big deal, using the `ReflectionPropertyAccessor` solve the issue. :+1: 

I still have an issue with persisting. With this listener:

```
final class BillingRecipientListener implements EventSubscriber
{
    /**
     * @var PropertyAccessor
     */
    private $accessor;

    /**
     * {@inheritdoc}
     */
    public function getSubscribedEvents()
    {
        return [
            Events::postLoad,
        ];
    }

    public function postLoad(LifecycleEventArgs $eventArgs): void
    {
        $object = $eventArgs->getObject();
        $manager = $eventArgs->getEntityManager();

        foreach ($manager->getClassMetadata(\get_class($object))->embeddedClasses as $field => $description) {
            if (BillingRecipient::class === $description['class']) {
                /** @var BillingRecipient $recipient */
                $recipient = $this->getAccessor()->getValue($object, $field);

                if (null !== $recipient->getCountryId()) {
                    $recipient->setCountry(
                        $manager->getRepository(Country::class)->findOneBy([
                            'id' => $recipient->getCountryId(),
                        ])
                    );
                }
            }
        }
    }

    private function getAccessor(): PropertyAccessor
    {
        if (null === $this->accessor) {
            $this->accessor = PropertyAccess::createPropertyAccessor();
        }

        return $this->accessor;
    }
}
```

And this fixtures file:

```
include:
    - user.yml
    - accounting.yml
    - country.yml

AppBundle\Embeddable\BillingRecipient:
    billing_recipient_user_default:
        name: '@user_default->fullname'
        address: <address()>
        country: '@country_france'
        company: <company()>
        siret: <siret()>

AppBundle\Entity\Invoice:
    invoice (template):
        version: 1  # TODO: Remove after issue https://git.nexylan.net/nexylan/n-admin/issues/455
        vat: 0.2
        recipient: '@billing_recipient_*'
        accounting: '@accounting_fr'
        isValid: true
        paid: true
        createdAt: <dateTimeBetween('- 5 years')>
        periodBegin: <dateTimeBetween('2016-03-01', '2016-03-01')>
        periodEnd: <dateTimeBetween('2016-03-31', '2016-03-31')>
        dueDate: <datetime()>
    invoice_user_default (extends invoice):
        customer: '@user_default'
        createdAt: <dateTimeBetween('2016-03-01', '2016-03-01')>
        paid: true

AppBundle\Entity\InvoiceItem:
    invoiceitem (template):
        name: <sentence()>
        refProduct: <regexify('[A-Z]{2}[A-Z0-9]{2,6}')>
        price: <randomFloat(2, 20, 200)>
        quantity: <numberBetween(1, 5)>
    invoiceitem_invoice_default_01  (extends invoiceitem):
        invoice: '@invoice_user_default'
        price: 139
        quantity: 1

AppBundle\Entity\Payment:
    payment_invoice_user_default_01:
        __construct:
            - 166.16
            - 'bank_transfer'
        invoice: '@invoice_user_default'
    payment_invoice_user_default_01:
        __construct:
            - 0.64
            - 'bank_transfer'
        invoice: '@invoice_user_default'
```

I got this error:

```
1) Tests\AppBundle\Controller\Billing\InvoiceControllerTest::testShow
TypeError: Argument 1 passed to AppBundle\Embeddable\BillingRecipient::setCountry() must be an instance of AppBundle\Entity\Country, null given, called in /code/src/AppBundle/Listener/BillingRecipientListener.php on line 52
```

I don't really understand. It looks like the entity is loaded by doctrine even if it's not persisted, resulting on a null result when the listener does the query.

> The issue that you have at the core is that you want to generate a graph of objects and persist it, but some of those objects requires to be persisted to be completed.

Exactly. :-)

> Alice 2 was kinda allowing that, but it was a very brittle process which was breaking often besides making it impossible to handle circular dependencies correctly.

I understand the problematic, but it introduces other issues. Don't we have any way to persist some of the entities with higher priority?

**Comment by theofidry** [comment]
>I assume it can be found with Doctrine metadata. I don't know for the other layers.

That would require nelmio/alice to be aware of Doctrine which is not the case (at least right now).

>I understand the problematic, but it introduces other issues. Don't we have any way to persist some of the entities with higher priority?

There is several ways: either do multiple loadings or using a custom PersisterLoader which gives you full control on how to persist stuff.

**Comment by Soullivaneuh** [comment]
> either do multiple loadings

Would be complicated. I just use the hautelook command and fixtures loading from liip functional testing.

> or using a custom PersisterLoader which gives you full control on how to persist stuff.

I might be blind, but I can't find anything about it on the documentation. :-)

**Comment by Soullivaneuh** [comment]
Hmm, it looks like the last error does not come from alice directly, and not this bundle either. I'm investigating.

**Comment by theofidry** [comment]
>I might be blind, but I can't find anything about it on the documentation. :-)

No it's just a good old Symfony service decoration :) You can declare your own service and use the same service name as the service you want to override to completely override it or use the `decorator` property (cf. the Sf doc)

**Comment by Soullivaneuh** [comment]
Ok, so it seems the issue is because the test database was not fully reset and the ID increment was not at 0.

So even if I set some IDs, they are not save as intended and the test is failing.

This is quite cumbersome, because now I have to reset the database each time before the test.

**Comment by Soullivaneuh** [comment]
I already use `dmaicher/doctrine-test-bundle` with `liip/functional-test-bundle` which implements nelmio/alice usage.

AFAIK, I didn't made anything else special. Right know, if I run a simple test with database reset from phpunit, it works. If I run it again just after this one without database reset, I have the error I pasted.

So I tried to remove the manual IDs and decorate the default loader:

```php
final class ClassPriorityLoader implements LoaderInterface
{
    private const HIGH_PRIORITY_CLASSES = [
        Accounting::class,
        Country::class,
    ];

    /**
     * @var LoaderInterface
     */
    private $loader;

    /**
     * @var SimpleLoader
     */
    private $simpleLoader;

    public function __construct(LoaderInterface $loader, SimpleLoader $simpleLoader)
    {
        $this->loader = $loader;
        $this->simpleLoader = $simpleLoader;
    }

    /**
     * {@inheritdoc}
     */
    public function load(array $fixturesFiles, array $parameters = [], array $objects = [], PurgeMode $purgeMode = null): array
    {
        $objects = $this->simpleLoader->load($fixturesFiles, $parameters, $objects, $purgeMode);
        $highPriorityObjects = [];

        foreach ($objects as $id => $object) {
            if (\in_array(ClassUtils::getClass($object), self::HIGH_PRIORITY_CLASSES, true)) {
                $highPriorityObjects[$id] = $object;
                unset($objects[$id]);
            }
        }

        dump($highPriorityObjects);
        dump($this->loader->load($fixturesFiles, $parameters, $highPriorityObjects, $purgeMode)); die;

        return array_merge(
            $this->loader->load($fixturesFiles, $parameters, $highPriorityObjects, $purgeMode),
            $this->loader->load($fixturesFiles, $parameters, $objects, $purgeMode)
        );
    }
}
```

The service definition:

```yaml
AppBundle\DataFixtures\Loader\ClassPriorityLoader:
    decorates: fidry_alice_data_fixtures.doctrine.persister_loader
    arguments:
        - '@AppBundle\DataFixtures\Loader\ClassPriorityLoader.inner'
        - '@fidry_alice_data_fixtures.loader.simple'
```

The first dump appeared during the test run but not the second and I ran into the same issue as described in https://github.com/theofidry/AliceDataFixtures/issues/94#issuecomment-391046611.

Did I miss something? :thinking:
