### ISSUE TITLE
[Error] Multiple non-persisted new entities were found through the given association graph

### ISSUE THREAD

**Issue by gnat42** [theofidry/AliceDataFixtures#95]
I'm stuck with trying to get some fixtures to load. Everything works until I add one set of entities at which point I get this error about new " A new entity was found through the relationship". I can build the same graph via a simple ContainerAwareCommand and it persists normally so I have no idea what's going on here.

Here are the fixtures:

```yml
# PracticeAndUsers.yml
---
NS\CoreDomain\Practice\Practice:
  unverified:
    __construct: [ '<company()>' ]
    street: '<streetAddress()>'
    city: '<city()>'
    province: '<state()>'
    postalCode: '<postcode()>'
    accountType: 'silver'
    verified: false
  practices{1..10}:
    __construct: [ '<company()>' ]
    street: '<streetAddress()>'
    city: '<city()>'
    province: "<state()>"
    postalCode: "<postcode()>"
    accountType: "<accountType()>"
    verified: true
    twilioNumber: '50%? <e164PhoneNumber()>'

NS\CoreDomain\Practice\User:
  unverifiedUser:
    __construct: [ "@unverified" ]
    name: '<name()>'
    email (unique): '<email()>'
    plainPassword: 1234567
  users{0..12}:
    __construct: [ "@practices*" ]
    name: '<name()>'
    email (unique): '<email()>'
    plainPassword: 1234567

# Clients.yml
---
NS\CoreDomain\Practice\AddressableEntity:
  addressableEntity{0..10}:
    __factory: { createPerson: [ '<lastName()>', '<firstName()>' ]}
  addressableEntity{11..30}:
    __construct: {createCorporation: [ '<company()>' ]}

NS\CoreDomain\Practice\Client:
  client{0..30}:
    __construct: [ '@practices*', '@addressableEntity*' ]

# MattersAndContracts.yml
---
NS\CoreDomain\Practice\Matter:
  realestate_matters{0..10}:
    __construct:
      0: ['@client*']
      1 (unique): '<bothify("RE-????-####")>'
      2: 'ns.realestate'
      3: '@users*'

# Everything loads fine if these are commented out
NS\CoreDomain\RealEstate\Contract:
  realestate_contracts{0..10}:
    __construct:
      0 (unique): '@realestate_matters*'
      1: 'purchase'
      2: false
```

Here's a snippet of command code that successfully creates the object I need without any error.

```php
        $practice = new Practice('Practice');
        $user = new User($practice);
        $user->setName('User Name');
        $user->setEmail($input->getArgument('email'));

        $person = AddressableEntity::createPerson('Noblet', 'Nathanael');
        $client = new Client($practice, $person);

        $matter = new Matter([$client], $input->getArgument('number'), MatterProvider::TYPE, $user);
        $contract = new Contract($matter, $input->getArgument('type'), false);

        $entityManager = $this->getContainer()->get('doctrine.orm.entity_manager');
        $entityManager->persist($user);
        $entityManager->persist($client);
        $entityManager->persist($practice);
        $entityManager->persist($matter);
        $entityManager->persist($contract);
        $entityManager->flush();
```
I've tried a few different things like changing the persisting order without any luck. Like I said I can do it manually so I'm confused what's going on.

**Comment by theofidry** [comment]
I would first try to:

- reduce the number of figures in order to identify the problematic relationship
- then try to identifier which properties being set causes the issue
- dump the graph of objects with the [Symfony VarDumper](https://symfony.com/doc/current/components/var_dumper.html) in order to check if the references of the objects are the ones you are expecting

Then it really depends on what's going on, it can be an issue in alice, your setters not being set like you expected, a clone somewhere in your code...

Also just double check if you are on the latests versions as well :)

Sorry if I cannot help more than that for now but it's really about your code until we have a clear reproducer

**Comment by gnat42** [comment]
Hello @theofidry 

* I checked my source code and nothing is cloned
* I made it so that there's only one realestate_contract but get the same issue
* I have hautelook/alice-bundle: v2.0.0 and theofidry/alice-data-fixtures: v1.0.1 which seem to be the latest
* I'll try to reduce everything to a simple set of objects to determine whats happening

Thank you for responding so quickly. Its a long weekend here so I won't be looking at this until probably Tuesday

**Comment by gnat42** [comment]
So I created a single yml file with a single object of each type

```yml
## YAML Template.
---
NS\CoreDomain\Practice\Practice:
  practice:
    __construct: [ '<company()>' ]
    street: '<streetAddress()>'
    city: '<city()>'
    province: "<state()>"
    postalCode: "<postcode()>"
    accountType: "<accountType()>"
    verified: true
    twilioNumber: '50%? <e164PhoneNumber()>'

NS\CoreDomain\Practice\User:
  user:
    __construct: [ "@practice" ]
    name: '<name()>'
    email (unique): '<email()>'
    plainPassword: 1234567

NS\CoreDomain\Practice\AddressableEntity:
  addressableEntity:
    __factory: { createPerson: [ '<lastName()>', '<firstName()>' ]}

NS\CoreDomain\Practice\Client:
  client:
    __construct: [ '@practice', '@addressableEntity' ]

NS\CoreDomain\Practice\Matter:
  realestate_matter:
    __construct:
      0: ['@client']
      1 (unique): '<bothify("RE-????-####")>'
      2: 'ns.realestate'
      3: '@user'

NS\CoreDomain\RealEstate\Contract:
  realestate_contract:
    __construct:
      0 (unique): '@realestate_matter'
      1: 'purchase'
      2: false
```
If the realestae_contract is not commented, I get the same error message. If I comment it, I get one of each object as expected.

They are the same objects too. For example, with the above I get the following error message:

```
 * A new entity was found through the relationship 'NS\CoreDomain\Practice\Client#practice' that was not configured to cascade persist operations for entity: Adams-Reichel....
 * A new entity was found through the relationship 'NS\CoreDomain\Practice\Matter#lawyer' that was not configured to cascade persist operations for entity: Dr. Samir Weimann DDS....
```
The name of the practice is Adams-Reichel which is the name the practice that gets successfully persisted when the realestate_contracts is commented out. Same goes for the lawyer.
